services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '3005:3005'
      - '5555:5555'
    volumes:
      - .:/app
      - nest_node_modules:/app/node_modules
    depends_on:
      - db
    command: bash -c "npx prisma migrate dev && npx prisma generate && npm run start:dev"
    networks:
      - nest_app
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_app

volumes:
  nest_node_modules:
  postgres_data:

networks:
  nest_app:
    driver: bridge
