services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
      - apps/api/.env.db
    ports:
      - '3005:3005'
      - '5555:5555'
    networks:
      - nest_app

networks:
  nest_app:
    driver: bridge
