services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - apps/api/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_app

volumes:
  postgres_data:

networks:
  nest_app:
    driver: bridge
